server:
  port: 8000
  tomcat:
    max-threads: 1000
    min-spare-threads: 30
  servlet:
    context-path: /ngt
spring:
  activemq:
    broker-url: tcp://192.168.0.167:61616
    user: admin
    password: admin
  thymeleaf:
    cache: false
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
   #redis配置
  redis:
    database: 0
    host: 192.168.0.167
    port: 6379
    password: 
    jedis:
      pool:
        max-idle: 8
    lettuce:
      pool:
        max-active: 8
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.0.167:3306/ngt?characterEncoding=utf8
    username: root
    password: root
    jdbcPool:
      maximumPoolSize: 30
      connectionTimeout: 30000
      idleTimeout: 600000
      maxLifetime: 1800000
      minimumIdle: 100
      initializationFailTimeout: 1
      validationTimeout: 5000
      leakDetectionThreshold: 0
logging:
  config: classpath:logback-spring.xml
  file: D:/logs/springboot.log
huaxing:
  file: 
    upload: e:/file/upload
    domain: http://file.huaxing.com/upload
  datasource:
    names: ds1,ds2
    ds1: 
      type: com.zaxxer.hikari.HikariDataSource
      driverClassName: com.mysql.jdbc.Driver
      url: jdbc:mysql://192.168.0.167:3306/ngt?characterEncoding=utf8
      username: root
      password: root
      jdbcPool:
        maximumPoolSize: 30
        connectionTimeout: 30000
        idleTimeout: 600000
        maxLifetime: 1800000
        minimumIdle: 100
        initializationFailTimeout: 1
        validationTimeout: 5000
        leakDetectionThreshold: 0
    ds2: 
      type: com.zaxxer.hikari.HikariDataSource
      driverClassName: com.mysql.jdbc.Driver
      url: jdbc:mysql://192.168.0.167:3306/ngt?characterEncoding=utf8
      username: root
      password: root
      jdbcPool:
        maximumPoolSize: 30
        connectionTimeout: 30000
        idleTimeout: 600000
        maxLifetime: 1800000
        minimumIdle: 100
        initializationFailTimeout: 1
        validationTimeout: 5000
        leakDetectionThreshold: 0